spring.config.import=classpath:commons.properties
spring.application.name=auth-service
server.port=8006
server.servlet.context-path=/auth-service
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger-ui.html
