default-tenant=${DEFAULT_TENANT:tenant_alpha}
allowed.tenants.request=tenant_alpha,tenant_beta
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
