spring.application.name=gateway
server.port=8007
allowed.tenants.request=tenant_alpha,tenant_beta
management.endpoints.web.exposure.include=health,info
microservice-1.service.base-url=http://localhost:8008/
auth-service.base-url=http://localhost:8006/
jwt.secret=${JWT_SECRET:change-me-please-change-me-12345}
spring.thymeleaf.cache=false
springdoc.swagger-ui.path=/swagger-ui.html
