spring.config.import=classpath:commons.properties
spring.application.name=microservice-1
server.port=8008
server.servlet.context-path=/microservice-1
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger-ui.html
