tenant.name=tenant_alpha
client.code=ALPHA
spring.datasource.url=jdbc:h2:mem:tenant_alpha;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.data.mongodb.database=tenant_alpha
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost
spring.data.mongodb.username=
spring.data.mongodb.password=
tenant.display.name=Tenant Alpha
